### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by StefanoGiu** [hemantkamalakar/google_fit_hass#1]
2020-04-17 17:09:56 ERROR (MainThread) [homeassistant.components.sensor] google_fit: Error on device update!
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\homeassistant\helpers\entity_platform.py", line 312, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "C:\Python38\lib\site-packages\homeassistant\helpers\entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "C:\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Python38\lib\site-packages\homeassistant\util\__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "C:\Python38\lib\site-packages\homeassistant\util\__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\custom_components\google_fit\sensor.py", line 568, in update
    for point in self._get_dataset(self.DATA_SOURCE)["point"]:
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\custom_components\google_fit\sensor.py", line 330, in _get_dataset
    return self._client.users().dataSources(). \
AttributeError: 'NoneType' object has no attribute 'users'

**Comment by hemantkamalakar** [comment]
Hello,
Please make sure that the _google_fit.token_ is generated in your config folder and you have followed the steps mentioned here https://www.home-assistant.io/integrations/calendar.google#prerequisites

**Comment by StefanoGiu** [comment]
I followed the instructions... I have a token but I get the error above...

**Comment by hemantkamalakar** [comment]
Please make sure that you can see data using the Google Fitness API.
https://developers.google.com/fit/rest/v1/reference/
https://developers.google.com/oauthplayground/

**Comment by hemantkamalakar** [comment]
Closing since there is no activity on this issue.
